version: '3.8'
services:
  api_gateway:
    image: chaios/api-gateway:latest
    ports:
    - 8000:8000
    environment:
    - ENVIRONMENT=production
    - LOG_LEVEL=INFO
    networks:
    - chaios-network
    healthcheck:
      test:
      - curl -f http://localhost:8000/health
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi
  knowledge_system:
    image: chaios/knowledge-system:latest
    ports:
    - 8003:8003
    environment:
    - ENVIRONMENT=production
    - KNOWLEDGE_DB_PATH=/data/knowledge.db
    networks:
    - chaios-network
    volumes:
    - knowledge-storage:/data
    deploy:
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 4Gi
  polymath_brain:
    image: chaios/polymath-brain:latest
    ports:
    - 8004:8004
    environment:
    - ENVIRONMENT=production
    - GPU_ENABLED=true
    networks:
    - chaios-network
    deploy:
      resources:
        requests:
          cpu: 1500m
          memory: 3Gi
        limits:
          cpu: 3000m
          memory: 6Gi
  cudnt_accelerator:
    image: chaios/cudnt-accelerator:latest
    ports:
    - 8005:8005
    environment:
    - ENVIRONMENT=production
    - CUDA_VISIBLE_DEVICES=0
    networks:
    - chaios-network
    deploy:
      resources:
        requests:
          cpu: 2000m
          memory: 4Gi
        limits:
          cpu: 4000m
          memory: 8Gi
  frontend:
    image: chaios/frontend:latest
    ports:
    - 80:80
    environment: []
    networks:
    - chaios-network
    deploy:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
  postgres:
    image: postgres:14-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=chaios
    - POSTGRES_USER=chaios
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
    - chaios-network
    volumes:
    - postgres-storage:/var/lib/postgresql/data
    deploy:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi
  redis:
    image: redis:7-alpine
    ports:
    - 6379:6379
    environment: []
    networks:
    - chaios-network
    volumes:
    - redis-storage:/data
    deploy:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
volumes:
  knowledge_storage: {}
  postgres_storage: {}
  redis_storage: {}
networks:
  chaios-network:
    driver: bridge
